services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-broker
    init: true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    command:
      - redpanda
      - start
      - --mode dev-container
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    volumes:
      - ./redpanda/data:/var/lib/redpanda/data
    ports:
      - "19092:19092"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-db
    init: true
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password123
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - ./clickhouse/init/01_create_log_table.sql:/docker-entrypoint-initdb.d/01_create_log_table.sql
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: tabix-ui
    ports:
      - "8080:80"
    environment:
      CLICKHOUSE_HOST: clickhouse-db
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password123

volumes:
  clickhouse_data:
    driver: local



