syntax = "proto3";

import "google/protobuf/timestamp.proto";

package logging;

// LogAggregatorService defines the RPC to accept logs.
service LogAggregatorService {
  rpc AcceptLog(AcceptLogRequest) returns (AcceptLogResponse);
}

// AcceptLogRequest encapsulates the log data.
message AcceptLogRequest {
  string trace_id = 1;
  LogLevel log_level = 2;
  string service_name = 3;
  google.protobuf.Timestamp timestamp = 4;
  string message = 5;
}

// AcceptLogResponse is the acknowledgement message.
message AcceptLogResponse {
  int32 response_code = 1;
  string message = 2;
}

// Standard log levels.
enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  DEBUG = 1;
  INFO = 2;
  WARN = 3;
  ERROR = 4;
}
